# Dart 官方 lint 规则（flutter_lints）
analyzer:
  exclude:
    - build/**
    - android/**
    - windows/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
